### ISSUE TITLE
The URLs for EfficientNet pretrained models are broken

### ISSUE THREAD

**Issue by felentovic** [hirotomusiker/cifar10_pytorch#1]
Hey, could you please update the URLs for EfficientNet pre-trained models.

The authors note:

 
>IMPORTANT NOTE: In the latest update, I switched hosting providers for the pretrained models, as the previous models were becoming extremely expensive to host. This will break old versions of the library. I apologize, but I cannot afford to keep serving the models on the old provider. 

And new links:

url_map_advprop = {
    'efficientnet-b0': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b0-b64d5a18.pth',
    'efficientnet-b1': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b1-0f3ce85a.pth',
    'efficientnet-b2': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b2-6e9d97e5.pth',
    'efficientnet-b3': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b3-cdd7c0f4.pth',
    'efficientnet-b4': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b4-44fb3a87.pth',
    'efficientnet-b5': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b5-86493f6b.pth',
    'efficientnet-b6': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b6-ac80338e.pth',
    'efficientnet-b7': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b7-4652b6dd.pth',
    'efficientnet-b8': 'https://github.com/lukemelas/EfficientNet-PyTorch/releases/download/1.0/adv-efficientnet-b8-22a8fe65.pth',
}

**Comment by hirotomusiker** [comment]
Thank you!
I am changing the efficientnet model part to load from the [timm](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/efficientnet.py) library. So we won't need the weights path catalog after the modification.
